# Frame constants
int32 FRAME_TORSO = 0
int32 FRAME_WORLD = 1
int32 FRAME_ROBOT = 2

# Request
string effector_name # e.g., "Arms", "LArm", "RArm"
geometry_msgs/Point point # The point to look at in the specified frame
int32 frame
float32 speed # Speed between 0.0 and 1.0
---